<!-- ===========================================================================
// cb-title		=	Page Level Titles (Title, Twitter, OG)
// cb-desc		=	Page Level Descriptions (Description, Twitter, OG)
// cb-image		=	Page Level Images (Twitter, OG)
// cb-style		=	Page level External Styles
​
​
** External Styles and Scripts **
If you want to add multiple styles or scripts use comma(',') to seperate url's
​
// cb-head-script	=	Page Level Head Script. Using this tag to put head level scripts
// cb-body-script	=	Page Level Body Script. Using this tag to put Scripts in end of footer or above the </body> tag
// cb-has-noindex	=	Using this tag to add noindex, nofollow meta to head. Use "True" to enable this meta.
​

** Page Styles **
// Use <style> tag to include page level styles after the Page script

​
** Header and Footer **
// app-header 		=	App header will add header to the page. 
//                  Need a white header in page use :hasInvert="true" attribute
//                  Need a basic header(without menu's) in page use :hasBasicHeader="true" attribute
// app-footer 		=	App footer will add footer to the page.
​
If you want to remove header or footer. Remove the "app-header" or "app-footer" tag, script url and components in scripts.
============================================================================ -->
<!-- ===========================================================================
Start: Main Template
============================================================================ -->
<template>
    <div>
      <!-- ===================================================================
      Start: Meta Section
      ==================================================================== -->
      <app-meta 
        :cb-title="'Manage Affiliate Marketing with Chargebee and FirstPromoter'" 
        :cb-desc="'Track and generate referral commissions for both recurring sales and one-time charges for your affiliates and resellers with FirstPromoter'" 
        :cb-url="'/integrations/firstpromoter/'" 
        :cb-image="''"
        :cb-style="'/static/website/version/styles/bootstrap.css,/static/website/version/styles/new.css'"
        :cb-head-script="''"
        :cb-body-script="''"
        :cb-has-noindex="false"
        :disable-bootstrap-css="false"
        :disable-header-footer-css="false" />
      <!-- ===================================================================
      End: Meta Section
      ==================================================================== -->
      <!-- ===================================================================
      Start: Header Section
      ==================================================================== -->
      <app-header :hasInvert="false" :hasBasicHeader="false" :hasBackToCareers="false" />
      <!-- ===================================================================
      End: Header Section
      ==================================================================== -->
      <!-- ===================================================================
      Start: Body Section
      ==================================================================== -->
      <div class="cb-body">
        <!-- Start Main Body Content -->
        <section class="container integration xero ff-acuminpro">
            <nav class="integration__breadcrumb">
                <a href="/integrations/">Integrations</a>
               /
                <span>FirstPromoter</span>
            </nav>
            <section class="integration__right">
                <h1>
                    Manage your Affiliate Marketing with FirstPromoter and Chargebee
                </h1>
                <div class="integration__intro">
                    <p>Most affiliate tracking tools are built around eCommerce, making it very difficult to handle even the basic use cases encountered by subscription businesses. They are not tied with  subscriptions and don't know how to handle subscription upgrades, downgrades, delayed credit card charges or cancellations.</p>
                    <br>
                    <p>FirstPromoter was built from the ground-up with subscription businesses in mind. FirstPromoter automatically adjusts commissions in case of upgrades or downgrades, automatically tracks free trials, cancellations and refunds, calculates Monthly Recurring Revenue generated by affiliates, let's you set different commissions for different pricing plans, and much more.</p>
                </div>  
                <br>
                <div class="integration__intro">
                    <h2>What will this integration solve?</h2><br>
                    <ul>
                        <li>Track and generate referral commissions for both recurring sales and one-time charges</li>
                        <li>Automatically create commissions for different subscription scenarios like upgrades, downgrades and cancellations</li>
                        <li>Generate promo codes and track your affiliate sales by just using coupon codes without any referral links or cookies</li>
                    </ul>
                </div> 
                    <br>
                <div class="integration__intro">
                    <h2>How to get started?</h2><br>
                    <p>Follow the steps <a href="https://help.firstpromoter.com/integrations/how-to-integrate-chargebee-with-firstpromoter" target="_blank">here</a> to get started with the integration.</p>
                </div>    
            </section>
            <section class="integration__leftmenu hidden-xs">
                <div class="integration__logo hidden-xs">
                    <div class="integration__logo-box" style="background-color:#fff; border: 1px solid #eee;">
                        <img src="/static/website/version/images/integrations/firstpromoter/logo.png" alt="FirstPromoter" style="width: 70%" />
                    </div>
                </div>
                <section class="integration__desc">
                    <p>
                        FirstPromoter is the first affordable affiliate tracking and management tool, designed and built exclusively for subscription businesses.
                    </p>
                </section>
                <a cn-mark-signup="true" href="/trial-signup/?ref=integrations_page" class="btn btn-primary">Sign Up for Chargebee</a>
                <nav class="integration__nav hidden-xs">
                    <a href="/pricing/">Pricing</a>
                    <a href="https://help.firstpromoter.com/integrations/how-to-integrate-chargebee-with-firstpromoter">Documentation</a>
                    <a href="/company/terms/">Terms of Service</a>
                    <a href="/privacy/">Privacy Policy</a>
                    <a href="https://support.chargebee.com/">Support</a>
                    <a href="http://status.chargebee.com/">Status</a>
                </nav>
            </section>
            <div class="clearfix"></div>
            <section class="integration--row">
                <div class="cb-useguide__tab cb-useguide__tab-alt">
                    <div>
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#tab1" role="tab" data-toggle="tab">Auto-generate commission for subscription</a>
                            </li>
                            <li role="presentation">
                                <a href="#tab2" role="tab" data-toggle="tab">Set commissions and create unique coupons</a>
                            </li>
                            <li role="presentation">
                                <a href="#tab3" role="tab" data-toggle="tab">Automate Email to your Affiliates</a>
                            </li>
                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="tab1">
                                <div class="row">
                                    <div class="col-sm-7">
                                        <img src="/static/website/version/images/integrations/firstpromoter/fp1.png" class="img-responsive" width="750" />
                                    </div>
                                    <div class="col-sm-4">
                                        <br><h3 class="visible-xs">Auto-generate commission for subscription</h3>
                                        <p>The biggest advantage of using Chargebee integration is the precise and safe tracking of all customer billing events - sales, upgrades, downgrades, refunds and cancellations. Moreover, traditional tools use javascript to track sales, a process which can be easily manipulated to generate fake commissions. With Chargebee integration, only when you get the sale confirmation from Chargebee we generate an actual commission, highly reducing the fraud risk.</p>
                                    </div>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="tab2">
                                <div class="row">
                                    <div class="col-sm-7">
                                        <img src="/static/website/version/images/integrations/firstpromoter/fp2.png" class="img-responsive"  width="650" />
                                    </div>
                                    <div class="col-sm-4">
                                        <br><h3 class="visible-xs">Set commissions and create unique coupons</h3>
                                        <p>Set commissions based on the pricing plans . FirstPromoter allows you to set up different commissions based on the plan id on Chargebee. You can also exclude very easy certain plans from generating commissions.</p>
                                        <p>With the Chargebee integration you can enable powerful tracking options  such as coupon code tracking - meaning you can assign a coupon code from Chargebee to an affiliate and when FirstPromoter detect a sale with that coupon code, you would know which affiliate generated the sale, without using referral links or cookies</p>
                                    </div>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="tab3">
                                <div class="row">
                                    <div class="col-sm-7">
                                        <img src="/static/website/version/images/integrations/firstpromoter/fp3.png" class="img-responsive" width="650" />
                                    </div>
                                    <div class="col-sm-4">
                                        <br><h3 class="visible-xs">Automate Email to Affiliates</h3>
                                        <p>You can automatically activate and on-board your new affiliates with pre-made drip emails. You can also send emails based on different triggers like when a payout is completed.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </section>
        <!-- End Main Body Content -->
      </div>
      <!-- ===================================================================
      End: Body Section
      ==================================================================== -->
      <!-- ===================================================================
      Start: Footer Section
      ==================================================================== -->
      <app-footer />
      <!-- ===================================================================
      End: Footer Section
      ==================================================================== -->
    </div>
  </template>
  <!-- ===========================================================================
  End: Main Template
  ============================================================================ -->
  <!-- ===========================================================================
  Start: Scripts Section
  ============================================================================ -->
  <script>
    import AppMeta from '~/components/AppMeta.vue';
    import AppHeader from '~/components/AppHeader.vue';
    import AppFooter from '~/components/AppFooter.vue';
    
    export default {
      components: {
        'app-meta': AppMeta,
        'app-header': AppHeader,
        'app-footer': AppFooter
      },
      // jQuery methods/functions should be placed inside the methods
      methods: {},
      // jQuery interaction should be placed inside the mounted method
      mounted() {
        $('.pr-tab__plan-inv').tooltip({
            'show': true,
            'placement': 'bottom'
        });
      }
    }
  </script>
  <!-- ===========================================================================
  End: Script Section
  ============================================================================ -->
  <!-- ===========================================================================
  Start: Style Section
  ============================================================================ -->
  <style type="text/css">
  </style>
  <!-- ===========================================================================
  End: Style Section
  ============================================================================ -->
