<template>    
    <section class="faq-block list-square">
        <div class="container block-space-sm">
            <h4 class="text-uppercase text-center block-space-xs"><strong>Frequently Asked Questions</strong></h4>
            <div class="row">
            <div class="col-md-6">
                <ul>
                <li>
                    <p><strong>Do I need to have a paid account in Avalara?</strong></p>
                    <p class="clearfix">Yes, a paid account in Avalara is necessary. But you can explore the different options and test your integration in a free sandbox before making any decision. Avalara's pricing structure is based on annual transaction usage, with plans that start as low as $9 per month so merchants of all sizes can benefit from sales tax automation.</p>
                </li>
                <li>
                    <p><strong>What are the benefits for Chargebee customers that use Avalara?</strong></p>
                    <p class="clearfix">Determining the correct sales tax rates for digital goods can be difficult. Chargebee merchants that use Avalara have peace of mind that they’re doing sales tax right, which allows them to focus on more important business goals.</p>
                </li>
                <li>
                    <p><strong>Which countries are supported by the Chargebee - Avalara integration?</strong></p>
                    <p class="clearfix">The integration supports multiple regions including the US, Canada, the EU, and ANZ</p>
                </li>
                <li>
                    <p><strong>Which address (Shipping or Billing Address) of a customer will be used to determine tax?</strong></p>
                    <p class="clearfix">Typically, Chargebee will consider a customer’s shipping address to calculate tax. In case a shipping address is unavailable, Chargebee would use the billing address to determine the tax.</p>
                </li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul>
                <li>
                    <p><strong>With the integration, will the tax rates be applied to existing subscriptions as well?</strong></p>
                    <p class="clearfix">The existing subscriptions will not witness changes in the tax rates. Before migrating to Avalara, Chargebee will validate the addresses of the current customers, and the correct rate will be applied during subscription renewal.</p>
                </li>
                <li>
                    <p><strong>Can I handle product-specific tax rates with Avalara?</strong></p>
                    <p class="clearfix">Yes, you can handle product-specific tax rates with Avalara, with tax codes that determine the tax rate for each product. Apart from this, taxable and non-taxable products will also be automatically differentiated using tax codes.</p>
                </li>
                <li>
                    <p><strong>Will Avalara help in the tax filing procedure?</strong></p>
                    <p class="clearfix">Yes, Avalara helps with tax filing procedure as well. If you’re planning to use Avalara for tax filing, all invoices and credit notes can be posted to Avalara as soon as they are generated by enabling the 'Post Document to Avalara' option.</p>
                </li>
                <li>
                    <p><strong>Will tax be calculated for the communications industry?</strong></p> 
                    <p class="clearfix">Yes, the Chargebee + Avalara integration gives you access to AvaTax for Communications. Simplify complex tax calculations for communications transactions. Stay up-to-date with changing tax rules for VoIP, streaming and IoT services automatically.</p>
                </li>
                </ul>
                <div style="margin:50px 40px">
                    <img src="/static/website/version/images/integrations/avalara/avalara-certificate.png" class="img-responsive" alt="Avalara Integration - Chargebee" width="130">
                </div> 
            </div>
            </div>
        </div>
    </section>
</template>
<script>
export default {
    
}
</script>

